/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function jsonValidate(payload: string): string
export function jsonIsAuthorized(payload: string): string
export class CedarEngine {
  static isAuthorized(check: string): string
}
